# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionlog',
            name='account',
        ),
        migrations.RemoveField(
            model_name='sessionlog',
            name='host_user_bind',
        ),
        migrations.DeleteModel(
            name='SessionLog',
        ),
    ]
