# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('timeout', models.IntegerField(default=300)),
                ('token_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Audit.Account')),
                ('host_user_bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Audit.HostUserBind')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set([('host_user_bind', 'token')]),
        ),
    ]
