# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0004_auto_20171011_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
