# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0006_auto_20171013_0346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasklog',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='host_user_bind',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='task',
        ),
        migrations.DeleteModel(
            name='TaskLog',
        ),
    ]
